### ISSUE TITLE
Add CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by Agrover112** [Agrover112/lazycheck#3]
I need an custom Code of Conduct file to be added to the following repository.

Adapt the CODE OF CONDUCT from here ----> https://www.contributor-covenant.org/version/2/0/code_of_conduct/

**Comment by Nikhil-1503** [comment]
Hi,
I would like to work on this.

**Comment by Agrover112** [comment]
@Nikhil-1503  Ok , but at least wait till 1st Oct 😅 for Hacktoberfest to raise an PR
